printer.host=192.168.68.105
printer.port=7125
printer.refresh-interval-ms=100
printer.domain=lan
printer.monitor-interval=0
printer.start-cooldown-seconds=5
printer.idle-stop-seconds=60
printer.stats-interval-ms=10000
printer.continue-prompt-ms=30000
