# The app will attempt to get this information from your printer, but you can set it directly here if you want
#printer.name=Snapmaker
#printer.model=U1

printer.host=192.168.68.105
printer.port=7125
printer.domain=lan
printer.monitor-interval=0

printer.refresh-interval-ms=100
printer.start-cooldown-seconds=5
printer.idle-stop-seconds=60
printer.stats-interval-ms=10000
printer.continue-prompt-ms=30000

# DANGER
# Set this to false if you want to have no security on the app.
# You probably shouldn't do this.
# DANGER
global.security.enabled=true

# OIDC properties are loaded via the "secure" profile (application-secure.properties)
# which is activated automatically when global.security.enabled is not false
